/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package id.npad93.p9;

import id.npad93.p9.Scenes.FirsScene;
import id.npad93.p9.Scenes.HomeScene;
import id.npad93.p9.Scenes.MainScene;
import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application {
    private Stage stage;

    @Override
    public void start(Stage mainStage) {
        stage = mainStage;

        //stage
        // FirsScene firsScene = new FirsScene(stage);
        // firsScene.show();
        MainScene mainScene = new MainScene(stage);
        mainScene.show();
        stage.setTitle("Calculator");
        stage.setResizable(false);
        stage.show();
    }

    public static void main(String[] args) {
        launch();
    }

}

