/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package id.npad93.p9;

import id.npad93.p9.Scenes.HomeScene;
import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application {
    private Stage stage;

    @Override
    public void start(Stage mainStage) {
        stage = mainStage;

        //stage
        HomeScene homeScene = new HomeScene(stage);
        homeScene.show();
        stage.setTitle("SolusiMager.id");
        stage.setResizable(false);
        stage.show();
    }

    public static void main(String[] args) {
        launch();
    }

}

